### ISSUE TITLE
Can you bump node to 16? I have builded 32x library

### ISSUE THREAD

**Issue by TheEVolk** [AmyrAhmady/samp-node#10]
While I was actively interested in all this, I compiled the 32-bit Node JS library and tried to implement it in this project. It turned out cruelly, but the timers did not work, and when trying to implement them, everything fell. Perhaps together we can do this?

**Comment by AmyrAhmady** [comment]
node 16 is not even LTS yet and it's in beta stage, my plan was getting either node@13 or node@14 built for this, I'd appreciate it if you do for these.

I don't have any interest in using node@16 yet, newer version means less support for older linux distros cause building with newer glibc and glibcxx

**Comment by TheEVolk** [comment]
OK, I'll try to build Node 14

**Comment by AmyrAhmady** [comment]
Do you think you can do that for both windows and linux?

**Comment by TheEVolk** [comment]
25.04.2021, 12:41, "iAmir" ***@***.***>:
Do you think you can do that for both windows and linux?

**Comment by AmyrAhmady** [comment]
@TheEVolk Any news on this?

**Comment by TheEVolk** [comment]
> @TheEVolk Any news on this?

Let's go to some manager for instant information exchange

**Comment by AmyrAhmady** [comment]
@TheEVolk here is my discord tag: iAmir#8100
you can also join our samp community discord in https://discord.gg/samp

**Comment by TheEVolk** [comment]
Check it 
https://disk.yandex.ru/d/Eqm3O-3PcJkCSA

**Comment by alextwothousand** [comment]
Is there any word on this?
I have Node 16 built, so, I would be happy to provide a build, or even attempt to build samp-node with 16.4.0 myself.

**Comment by AmyrAhmady** [comment]
@alextwothousand would be nice if you try building samp-node with newer node yourself
the amount of API changes in node is too much that it's not really an easy task, not a "replace binaries and build" solution

**Comment by TheEVolk** [comment]
> replace binaries and build
I know :)

**Comment by sklawik** [comment]
Please update it at least to node v13/14. Plugin uses now v10.19.1-pre when most popular packets like Prisma support only < v12 and not lower. (https://preview.npmjs.com/package/prisma?activeTab=readme)
I found out the project is perfect and all I need to start project is newer version, I'm willing to help making it but never tinkered in such thing.

**Comment by AmyrAhmady** [comment]
@Hype02 one day I will, I am currently busy with another project, but I will do this and upgrade node version a day I'm free

**Comment by TheEVolk** [comment]
Any news?

**Comment by alextwothousand** [comment]
Would be great if this was done.

**Comment by ghosty2004** [comment]
Yes.. Any news? I need node >= v12

**Comment by AmyrAhmady** [comment]
Within next weeks/days we might launch our main project, so we are mostly focused on that at the moment
updating samp-node with latest or higher nodejs version requires a lot of implementation changes due to huge API compatibility break (which is fair anyway I don't blame them)

I will try updating samp-node first then I will go for omp-node right after that without hesitation and will probably abandon this one since we won't be needing it anyway

Thank you guys for your support and patience @alextwothousand @TheEVolk @Ghosty2004 @Hype02

**Comment by AmyrAhmady** [comment]
@Hype02 @TheEVolk @Ghosty2004 @alextwothousand it is upgraded to node v16 now, you may wanna give it a try and test it out
