### ISSUE TITLE
In release 1.2.0 SAMPNode_CallEvent crashes server

### ISSUE THREAD

**Issue by storme-dev** [AmyrAhmady/samp-node#11]
SAMPNode_CallEvent worked in 1.1.0 version, but in 1.2.0 it causes server crash. logs are empty, only crashinfo.txt:

Loaded Modules:

samp-server.exe	A: 0x00400000 - 0x00519000	(C:\Projects\SAMP-NODE(notmy)\samp-server.exe)

ntdll.dll	A: 0x76E70000 - 0x7700A000	(C:\WINDOWS\SYSTEM32\ntdll.dll)

KERNEL32.DLL	A: 0x76760000 - 0x76840000	(C:\WINDOWS\System32\KERNEL32.DLL)

KERNELBASE.dll	A: 0x76560000 - 0x7675F000	(C:\WINDOWS\System32\KERNELBASE.dll)

SHELL32.dll	A: 0x75E40000 - 0x763BB000	(C:\WINDOWS\System32\SHELL32.dll)

ucrtbase.dll	A: 0x75A00000 - 0x75B20000	(C:\WINDOWS\System32\ucrtbase.dll)

cfgmgr32.dll	A: 0x76BA0000 - 0x76BDB000	(C:\WINDOWS\System32\cfgmgr32.dll)

shcore.dll	A: 0x74830000 - 0x748B3000	(C:\WINDOWS\System32\shcore.dll)

msvcrt.dll	A: 0x76400000 - 0x764BF000	(C:\WINDOWS\System32\msvcrt.dll)

RPCRT4.dll	A: 0x74660000 - 0x7471B000	(C:\WINDOWS\System32\RPCRT4.dll)

SspiCli.dll	A: 0x74630000 - 0x74655000	(C:\WINDOWS\System32\SspiCli.dll)

CRYPTBASE.dll	A: 0x74620000 - 0x7462A000	(C:\WINDOWS\System32\CRYPTBASE.dll)

bcryptPrimitives.dll	A: 0x76840000 - 0x768A0000	(C:\WINDOWS\System32\bcryptPrimitives.dll)

sechost.dll	A: 0x748C0000 - 0x74936000	(C:\WINDOWS\System32\sechost.dll)

combase.dll	A: 0x74DC0000 - 0x75037000	(C:\WINDOWS\System32\combase.dll)

windows.storage.dll	A: 0x75440000 - 0x759FF000	(C:\WINDOWS\System32\windows.storage.dll)

msvcp_win.dll	A: 0x74730000 - 0x747AC000	(C:\WINDOWS\System32\msvcp_win.dll)

advapi32.dll	A: 0x747B0000 - 0x74829000	(C:\WINDOWS\System32\advapi32.dll)

profapi.dll	A: 0x75C70000 - 0x75C87000	(C:\WINDOWS\System32\profapi.dll)

powrprof.dll	A: 0x75C10000 - 0x75C53000	(C:\WINDOWS\System32\powrprof.dll)

UMPDC.dll	A: 0x75C60000 - 0x75C6D000	(C:\WINDOWS\System32\UMPDC.dll)

shlwapi.dll	A: 0x75CF0000 - 0x75D34000	(C:\WINDOWS\System32\shlwapi.dll)

GDI32.dll	A: 0x74940000 - 0x74961000	(C:\WINDOWS\System32\GDI32.dll)

win32u.dll	A: 0x76C10000 - 0x76C27000	(C:\WINDOWS\System32\win32u.dll)

gdi32full.dll	A: 0x76C90000 - 0x76DED000	(C:\WINDOWS\System32\gdi32full.dll)

USER32.dll	A: 0x75150000 - 0x752E8000	(C:\WINDOWS\System32\USER32.dll)

kernel.appcore.dll	A: 0x752F0000 - 0x752FF000	(C:\WINDOWS\System32\kernel.appcore.dll)

cryptsp.dll	A: 0x763E0000 - 0x763F3000	(C:\WINDOWS\System32\cryptsp.dll)

WSOCK32.dll	A: 0x742A0000 - 0x742A8000	(C:\WINDOWS\SYSTEM32\WSOCK32.dll)

WINMM.dll	A: 0x74320000 - 0x74344000	(C:\WINDOWS\SYSTEM32\WINMM.dll)

WS2_32.dll	A: 0x76E00000 - 0x76E5E000	(C:\WINDOWS\System32\WS2_32.dll)

winmmbase.dll	A: 0x740A0000 - 0x740C3000	(C:\WINDOWS\SYSTEM32\winmmbase.dll)

IMM32.DLL	A: 0x76BE0000 - 0x76C05000	(C:\WINDOWS\System32\IMM32.DLL)

samp-node.DLL	A: 0x74260000 - 0x74294000	(C:\Projects\SAMP-NODE(notmy)\plugins\samp-node.DLL)

MSVCP140.dll	A: 0x6A000000 - 0x6A071000	(C:\WINDOWS\SYSTEM32\MSVCP140.dll)

VCRUNTIME140.dll	A: 0x6BB40000 - 0x6BB54000	(C:\WINDOWS\SYSTEM32\VCRUNTIME140.dll)

node.dll	A: 0x5E650000 - 0x5FA89000	(C:\Projects\SAMP-NODE(notmy)\node.dll)

PSAPI.DLL	A: 0x74720000 - 0x74726000	(C:\WINDOWS\System32\PSAPI.DLL)

CRYPT32.dll	A: 0x75040000 - 0x75141000	(C:\WINDOWS\System32\CRYPT32.dll)

MSASN1.dll	A: 0x76DF0000 - 0x76DFE000	(C:\WINDOWS\System32\MSASN1.dll)

bcrypt.dll	A: 0x763C0000 - 0x763D9000	(C:\WINDOWS\System32\bcrypt.dll)

IPHLPAPI.DLL	A: 0x743B0000 - 0x743E2000	(C:\WINDOWS\SYSTEM32\IPHLPAPI.DLL)

dbghelp.dll	A: 0x73E40000 - 0x73FCF000	(C:\WINDOWS\SYSTEM32\dbghelp.dll)

USERENV.dll	A: 0x734F0000 - 0x7350E000	(C:\WINDOWS\SYSTEM32\USERENV.dll)

mswsock.dll	A: 0x722F0000 - 0x72342000	(C:\WINDOWS\system32\mswsock.dll)

streamer.DLL	A: 0x74120000 - 0x74187000	(C:\Projects\SAMP-NODE(notmy)\plugins\streamer.DLL)

napinsp.dll	A: 0x698C0000 - 0x698D1000	(C:\WINDOWS\system32\napinsp.dll)

pnrpnsp.dll	A: 0x695B0000 - 0x695C6000	(C:\WINDOWS\system32\pnrpnsp.dll)

DNSAPI.dll	A: 0x72350000 - 0x723E3000	(C:\WINDOWS\SYSTEM32\DNSAPI.dll)

NSI.dll	A: 0x764C0000 - 0x764C7000	(C:\WINDOWS\System32\NSI.dll)

winrnr.dll	A: 0x6C800000 - 0x6C80B000	(C:\WINDOWS\System32\winrnr.dll)

NLAapi.dll	A: 0x69590000 - 0x695A6000	(C:\WINDOWS\system32\NLAapi.dll)

wshbth.dll	A: 0x6BEF0000 - 0x6BF00000	(C:\WINDOWS\system32\wshbth.dll)

mdnsNSP.dll	A: 0x6A3C0000 - 0x6A3E1000	(C:\Program Files (x86)\Bonjour\mdnsNSP.dll)

rasadhlp.dll	A: 0x71690000 - 0x71698000	(C:\Windows\System32\rasadhlp.dll)

**Comment by AmyrAhmady** [comment]
Please use 1.10 for now, I need to fix a few bug reports I've received for 1.2.0 first, for the matter I will just remove it from releases for now

**Comment by AmyrAhmady** [comment]
fixed in #15 thanks @plutalov
