### ISSUE TITLE
Sampctl: cannot read from file: "samp-node" - windows

### ISSUE THREAD

**Issue by erfanasbari** [AmyrAhmady/samp-node#13]
Hi. 
This error happens during build time because samp-node.inc is not included in `dependencies/.resources` directory.
I think It's because of the misspelling of `samp_node.inc`(it should be `samp-node.inc`) [here](https://github.com/AmyrAhmady/samp-node/blob/a19023f919b22f915660dd068cc7e381cf3a33d5/pawn.json#L35)

I forked the repo and fixed the typo then installed the package from my forked repo but `samp-node.inc` was not included in `.resources`. (I don't know much about Sampctl and how the `.resources` directory is generated)

Thanks for the great plugin. Khaste nabashi

**Comment by AmyrAhmady** [comment]
fixed
