### ISSUE TITLE
Server crash when I use discord.js 

### ISSUE THREAD

**Issue by ghosty2004** [AmyrAhmady/samp-node#17]
I'm using **discord.js v13.0.0** module and randomly the server crash with **Segmentation fault**.
It's possible to debug the crash ? I'm using the latest version of **samp-node**

**Comment by AmyrAhmady** [comment]
Would be great to post a simple code so we can reproduce the crash as well and debug it

**Comment by ghosty2004** [comment]
I'm using a try-catch in the code.. So I think it's impossible for crashing by this reason... I think it's from module **discord.js**

**Comment by alextwothousand** [comment]
Regardless of what you think the cause is, a code snippet will have to be posted, to allow for debugging to occur.

**Comment by AmyrAhmady** [comment]
@Ghosty2004 it can be still possible due to implementations in samp-node
I'd be glad if you show me a simple usage of what you did 🙂 
you are free to close the issue if you still insist this was a mistake, but again, it would be nicer to test it myself as well

**Comment by ghosty2004** [comment]
I think that I was fixed. I will close this issue.
