### ISSUE TITLE
Plugin loading failed

### ISSUE THREAD

**Issue by adri1336** [AmyrAhmady/samp-node#4]
Plugin loading in Windows is failing:
` Loading plugin: samp-node
  Failed.`

I have installed Microsoft Visual C++ 2015-2019 Redistributable x86 and x64 and node.dll is in server root directory.

**Comment by AmyrAhmady** [comment]
I know about this behaviour, and it will be fixed on next version samp-node v2

The reason it is failing is it does not generate config files automatically so you have to do it manually by your own, please check wiki for documentations and more info about config files (the necessary one is samp-node.json which should be in server root directory)

**Comment by adri1336** [comment]
Fixed, thank you
