### ISSUE TITLE
Failed loading plugin 

### ISSUE THREAD

**Issue by tripoloski-it** [AmyrAhmady/samp-node#7]
```
----------
Loaded log file: server_log.txt.
----------

SA-MP Dedicated Server
----------------------
v0.3.7-R2, (C)2005-2015 SA-MP Team

[07:55:24] 
[07:55:24] Server Plugins
[07:55:24] --------------
[07:55:24]  Loading plugin: samp-node
[07:55:24]   Failed.
[07:55:24]  Loaded 0 plugins.
```
![изображение](https://user-images.githubusercontent.com/48046493/108459648-219d2e80-7288-11eb-96c8-4599fe95dfe0.png)
![изображение](https://user-images.githubusercontent.com/48046493/108459670-2d88f080-7288-11eb-8813-f171668ac4bf.png)

# server.cfg
```
lanmode 0
rcon_password rconpassword
maxplayers 50
port 7777
hostname SomeName
gamemode0 index
time
announce 0
plugins samp-node
query 1
weburl https://site.com
maxnpc 0
onfoot_rate 40
incar_rate 40
weapon_rate 40
stream_distance 300.0
stream_rate 1000


```

**Comment by Kabo0m** [comment]
@ADRFranklin @AmyrAhmady  I'm also having problems to run a server with this plugin, with the same output.

**Comment by AmyrAhmady** [comment]
you need samp-node 's config file, read wiki and it will tell you how to set it up properly

**Comment by AmyrAhmady** [comment]
this now shows an error regarding not having a config file on startup
